config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title,presence:true,length: { minimum:5 }
    validates :text,presence:true,length: { in:5..145 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article=Article.new
  end

  def edit
    @article=Article.find(params[:id])
  end

  def create
    #render plain: params[:article].inspect
    #@article = Article.new(params[:article])
    @article = Article.new(article_params)

    #@article.save
    #redirect_to @article

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article=Article.find(params[:id])
    # @article.update(title: 'A new title') 仅更新title属性 update_attribute也是可以的 http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
    
  end

  private
    def article_params
      params.require(:article).permit(:title,:text)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>编辑文章</h1>
<%= form_for(@article,method: :patch) do |f| %>

    <% if @article.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@article.errors.count,'error') %> prohibited
        this article from being saved:
            </h2>
            <ul>
                <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    

    <p>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :text %>
        <%= f.text_area :text %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>
<%= link_to '返回',articles_path %>

app/views/articles/index.html.erb
<h1>文章列表</h1>
<%= link_to '添加新文章',new_article_path %>
<%= link_to '返回首页',root_path %>
<table>
    <tr>
        <th>Title</th>
        <th>Text</th>
    </tr>
    <% @articles.each do |article| %>
    <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= link_to 'show',article_path(article) %></td>
        <td><%= link_to 'edit',edit_article_path(article) %></td>
    </tr>
    <% end %>
    
</table>

app/views/articles/new.html.erb
<h1>添加新文章</h1>
<%= form_for :article,url: articles_path do |f| %>

    <% if @article.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@article.errors.count,'error') %> prohibited
        this article from being saved:
            </h2>
            <ul>
                <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    

    <p>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :text %>
        <%= f.text_area :text %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>
<%= link_to '返回',articles_path %>

app/views/articles/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @article.title %>
</p>
<p>
    <strong>Text:</strong>
    <%= @article.text %>
    
</p>
<%= link_to '返回',articles_path %>
<%= link_to '编辑',edit_article_path(@article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Awesomesite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<hr>
<h3>Hello Ruby On Rails</h3>
<pre>
          .----.
       _.'__    `.
   .--($)($$)---/#\
 .' @          /###\
 :         ,   #####
  `-..__.-' _.-\###/
        `;_:    `"'
      .'"""""`.
     /,  ya , \\
    //   RoR!  \\
    `-._______.-'
    ___`. | .'___
   (______|______) 
</pre>
<%= link_to '所有文章列表',controller:'articles' %>